# Generated by Django 2.0.3 on 2018-04-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_activation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
